version: '3'

networks:
  mynetwork:


services:
  database:
    image: mysql:5.7
    container_name: database
    restart: always
    environment:
      MYSQL_DATABASE: 'battleship'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
    - '3306:3306'
    volumes:
      - ./../../../../db:/var/lib/mysql
      - "./init-db/init-db.sql:/docker-entrypoint-initdb.d/1.sql:ro"
    networks:
      - mynetwork

  spring-battleship:
    image: feczkob/battleship:latest
    container_name: spring-battleship
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mysql://database:3306/battleship?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=true"
      MYSQL_HOST: database
    ports:
      - "80:8080"
    networks:
      - mynetwork
    depends_on:
      - database
    restart: on-failure