version: '3'

networks:
  mynetwork:


services:
  database:
    image: mysql:5.7
    container_name: database
    restart: always
    environment:
      MYSQL_DATABASE: 'battleship'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
    - '3306:3306'
    volumes:
      - ./../../../../db:/var/lib/mysql
    networks:
      - mynetwork

  spring-battleship:
    image: feczkob/battleship:battleship-1.0
    container_name: spring-battleship
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mysql://database:3306/battleship?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=true"
    ports:
      - "8080:8080"
    networks:
      - mynetwork
    depends_on:
      - database